# # Default application configuration that all configurations inherit from.
linters:
#   BorderZero:
#     enabled: true

#   CapitalizationInSelector:
#     enabled: true

#   ColorKeyword:
#     enabled: true

   Comment:
     enabled: false

#   DebugStatement:
#     enabled: true

#   DeclarationOrder:
#     enabled: false

#   DuplicateProperty:
#     enabled: true

#   EmptyLineBetweenBlocks:
#     enabled: true
#     ignore_single_line_blocks: true

#   EmptyRule:
#     enabled: true

#   FinalNewline:
#     enabled: true
#     present: true

   HexFormat:
     enabled: false

#   IdWithExtraneousSelector:
#     enabled: true

   Indentation:
     enabled: true
     width: 1

#   LeadingZero:
#     enabled: true
#     style: exclude_zero # or 'include_zero'

#   MergeableSelector:
#     enabled: true
#     force_nesting: true

#   NameFormat:
#     enabled: true
#     convention: hyphenated_lowercase # or 'BEM', or a regex pattern

   PlaceholderInExtend:
     enabled: false

   PropertySortOrder:
     enabled: false

#   PropertySpelling:
#     enabled: true
#     extra_properties: []

#   SelectorDepth:
#     enabled: true
#     max_depth: 3

#   Shorthand:
#     enabled: true

#   SingleLinePerSelector:
#     enabled: true

#   SpaceAfterComma:
#     enabled: true

#   SpaceAfterPropertyColon:
#     enabled: true

#   SpaceAfterPropertyName:
#     enabled: true

#   SpaceBeforeBrace:
#     enabled: true
#     allow_single_line_padding: false

#   SpaceBetweenParens:
#     enabled: true
#     spaces: 0

   StringQuotes:
     enabled: false
#     style: single_quotes # or double_quotes

#   TrailingSemicolonAfterPropertyValue:
#     enabled: true

#   UnnecessaryMantissa:
#     enabled: true

#   UrlFormat:
#     enabled: true

#   UrlQuotes:
#     enabled: true

#   ZeroUnit:
#     enabled: true

#   Compass::*:
#     enabled: false